name: Building Program
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  call-i386-zhuangzhuang:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: i386-zhuangzhuang
      arch: i386
      rootfs-codename: trixie
      rootfs-source: https://deb.debian.org/debian/
      gxde-codename: lizhi
      gxde-codename-upload: zhuangzhuang
